[project]
name = "proyecto-final"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12" 
dependencies = [
    "folium>=0.19.6",
    "ipykernel>=6.29.5",
    "ipyleaflet>=0.19.2",
    "ipympl>=0.9.7",
    "markdown>=3.8",
    "matplotlib>=3.10.3",
    "nbformat>=5.10.4",
    "pandas>=2.2.3",
    "plotly>=6.1.1",
    "radicli>=0.0.25",
    "scikit-learn>=1.6.1",
    "statsmodels>=0.14.4",
    "streamlit>=1.45.1",
    "streamlit-folium>=0.25.0",
    "watchdog>=6.0.0",
    "xarray>=2025.4.0",
    "xgboost>=3.0.1",
<<<<<<< HEAD
    "zarr>=3.0.8"
=======
    "zarr>=3.0.8",
    "pyproj>=3.7.1",
    "s3fs>=2025.5.1",
    "shapely>=2.1.1",
    "torch>=2.7.0",
    "tqdm>=4.67.1",
>>>>>>> e56d0feff378da3370026594f89d73f2bae039af
]

[tool.uv.sources]
torch = [
  { index = "pytorch-cu128", marker = "sys_platform == 'linux'" },
]

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true
